[build]
target = "xtensa-esp32-espidf" # Change this if using ESP32-S3 or C3

[target.xtensa-esp32-espidf]
linker = "ldproxy"

[env]
MCU = "esp32"
# This ensures the ESP-IDF version is matched
ESP_IDF_VERSION = "v5.1"
